### PR TITLE
day selector

### PR DESCRIPTION
**Pull request by sojinantony01**
Day selector

### CODE REVIEW

**Comment by shivam178** [comment]
@sojinantony01 Functionality-wise, it's good. 
Working as expected.
But CSS-wise, not so good.
A few suggestions:
- Too long and uses the screen y-axis to scroll too much... it should have its own container, with a max height, which is scrollable.
- Text inside dropdown is better left aligned.
- Selections instead of ticks can be color-selected as shown in the picture.
- Width should be similar to input width, and the dropdown container should align with input.

https://github.com/user-attachments/assets/21f8e9f4-4519-403b-92ee-ca9b65bc5cba

**Comment by shivam178** [comment]
Also, selecting 1 day in the dropdown is similar to the first radio button input.
We should remove the first input?

**Comment by sojinantony01** [comment]
Thanks @shivam178 
> Functionality-wise, it's good. Working as expected.
Thanks for confirming this, it was the hard part 😄 
I will correct the CSS part this Saturday

>  Also, selecting 1 day in the dropdown is similar to the first radio button input.
> We should remove the first input?

Hmm, yes that is a good point, 
For now let it be there because people already using it with translation, We can remove it in next major version

**Comment by sojinantony01** [comment]
Hi @shivam178 
I am sorry. I was away due to the vacations!.
I have updated the PR and i hope i fixed the comments.
Could you please have a look.

**Comment by shivam178** [comment]
Awesome work, thanks @sojinantony01 👍

**Pull request merged**
